services:
  postgres:
    image: postgres:16-alpine
    container_name: sh-postgres
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 300M

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: sh-rabbitmq
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      resources:
        limits:
          memory: 400M

  redis:
    image: redis:7.2-alpine
    container_name: sh-redis
    restart: on-failure
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 100M

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    container_name: sh-keycloak
    command: start-dev --import-realm
    restart: on-failure
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./infra/keycloak/realm-export.json:/opt/keycloak/data/import/realm.json
    deploy:
      resources:
        limits:
          memory: 700M

  # Aplikacje
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: api-gateway/target/*.jar
    container_name: sh-gateway
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - keycloak
    environment:
      - AUTH_SERVER_URL=http://sh-keycloak:8080
      - PATIENT_SERVICE_URL=http://sh-patient:8081
      - APPOINTMENT_SERVICE_URL=http://sh-appointment:8082
      - BILLING_SERVICE_URL=http://sh-billing:8083
      - DEVICE_SERVICE_URL=http://sh-device:8085
      - JAVA_OPTS=-Xmx384m -Xms128m
    deploy:
      resources:
        limits:
          memory: 512M

  patient-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: patient/target/*.jar
    container_name: sh-patient
    restart: on-failure
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - DB_HOST=sh-postgres
      - DB_PORT=5432
      - MQ_HOST=sh-rabbitmq
      - AUTH_SERVER_URL=http://sh-keycloak:8080
      - JAVA_OPTS=-Xmx192m -Xms128m
    deploy:
      resources:
        limits:
          memory: 256M

  appointment-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: appointment/target/*.jar
    container_name: sh-appointment
    restart: on-failure
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      - DB_HOST=sh-postgres
      - DB_PORT=5432
      - MQ_HOST=sh-rabbitmq
      - PATIENT_SERVICE_URL=http://sh-patient:8081
      - AUTH_SERVER_URL=http://sh-keycloak:8080
      - JAVA_OPTS=-Xmx192m -Xms128m
    deploy:
      resources:
        limits:
          memory: 256M

  billing-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: billing/target/*.jar
    container_name: sh-billing
    restart: on-failure
    ports:
      - "8083:8083"
    depends_on:
      - postgres
    environment:
      - DB_HOST=sh-postgres
      - DB_PORT=5432
      - MQ_HOST=sh-rabbitmq
      - AUTH_SERVER_URL=http://sh-keycloak:8080
      - JAVA_OPTS=-Xmx192m -Xms128m
    deploy:
      resources:
        limits:
          memory: 256M

  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: notification/target/*.jar
    container_name: sh-notification
    restart: on-failure
    ports:
      - "8084:8084"
    depends_on:
      - rabbitmq
    environment:
      - MQ_HOST=sh-rabbitmq
      - AUTH_SERVER_URL=http://sh-keycloak:8080
      - JAVA_OPTS=-Xmx192m -Xms128m
    deploy:
      resources:
        limits:
          memory: 300M

  device-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: device/target/*.jar
    container_name: sh-device
    restart: on-failure
    ports:
      - "8085:8085"
    depends_on:
      - redis
      - postgres
    environment:
      - DB_HOST=sh-postgres
      - DB_PORT=5432
      - MQ_HOST=sh-rabbitmq
      - REDIS_HOST=sh-redis
      - AUTH_SERVER_URL=http://sh-keycloak:8080
      - JAVA_OPTS=-Xmx192m -Xms128m
    deploy:
      resources:
        limits:
          memory: 256M

  analytics-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: analytics/target/*.jar
    container_name: sh-analytics
    restart: on-failure
    ports:
      - "8086:8086"
    depends_on:
      - postgres
    environment:
      - DB_HOST=sh-postgres
      - DB_PORT=5432
      - MQ_HOST=sh-rabbitmq
      - AUTH_SERVER_URL=http://sh-keycloak:8080
      - JAVA_OPTS=-Xmx192m -Xms128m
    deploy:
      resources:
        limits:
          memory: 256M

  prometheus:
    image: prom/prometheus:latest
    container_name: sh-prometheus
    restart: on-failure
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    deploy:
      resources:
        limits:
          memory: 256M

  grafana:
    image: grafana/grafana:latest
    container_name: sh-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    deploy:
      resources:
        limits:
          memory: 256M

volumes:
  postgres_data: