server:
  port: 8080

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: api-gateway
            client-secret: Ysg9frla1hvlmX3LnnPOEoRgiBlLsJEY
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/smarthealth
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/smarthealth
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: http://localhost:8081
          predicates:
            - Path=/patient/**
        - id: appointment-service
          uri: http://localhost:8082
          predicates:
            - Path=/appointment/**
        - id: billing-service
          uri: http://localhost:8083
          predicates:
            - Path=/billing/**
        - id: device-service
          uri: http://127.0.0.1:8085
          predicates:
            - Path=/device/**
        - id: analytics-service
          uri: http://127.0.0.1:8086
          predicates:
            - Path=/analytics/**

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus