server:
  port: 8080

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/smarthealth
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: analytics-service
          uri: ${ANALYTICS_SERVICE_URL:http://localhost:8086}
          predicates:
            - Path=/analytics/**
        - id: patient-service
          uri: ${PATIENT_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/patient/**
        - id: appointment-service
          uri: ${APPOINTMENT_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/appointment/**
        - id: billing-service
          uri: ${BILLING_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/billing/**
        - id: device-service
          uri: ${DEVICE_SERVICE_URL:http://localhost:8085}
          predicates:
            - Path=/device/**
          filters:
            - RewritePath=/device/(?<segment>.*),/$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true