server:
  port: 8081

spring:
  application:
    name: patient-service
  config:
    import: "optional:aws-parameterstore:/config/patient-service/"
  cloud:
    aws:
      parameterstore:
        endpoint: ${AWS_ENDPOINT:http://localhost:4566}
        region: us-east-1
      credentials:
        access-key: test
        secret-key: test
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/patient_db
    driver-class-name: org.postgresql.Driver
    # Username and Password loaded from AWS Parameter Store
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: ${MQ_HOST:localhost}
    port: 5672


management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}