server:
  port: 8084

spring:
  application:
    name: notification-service
  rabbitmq:
    host: ${MQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest


management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}
