server:
  port: 8086

spring:
  application:
    name: analytics-service
  datasource:
    url: jdbc:postgresql://localhost:5436/analytics_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus